# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('lastWeight', models.IntegerField()),
                ('wtDelta', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter', models.CharField(max_length=4, unique=True)),
                ('room', models.CharField(choices=[('A', 'Room A'), ('B', 'Room B'), ('C', 'Room C'), ('D', 'Room D')], max_length=6)),
                ('arrival', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='kitten',
            name='litter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeding.Litter'),
        ),
    ]
