# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_auto_20160106_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='foodtype',
            field=models.CharField(choices=[('gruel', 'Gruel'), ('wet', 'Wet'), ('dry', 'Dry'), ('wd', 'Wet/Dry')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='litter',
            name='last_feed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 7, 6, 17, 30, 530533)),
            preserve_default=False,
        ),
    ]
