# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0003_auto_20160107_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litter',
            name='foodtype',
            field=models.CharField(choices=[('2', 'Gruel'), ('3', 'Wet'), ('5', 'Dry'), ('4', 'Wet/Dry')], max_length=12),
        ),
    ]
