# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0004_auto_20160107_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='next_feed',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 7, 11, 55, 55, 609114), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='litter',
            name='foodtype',
            field=models.IntegerField(choices=[(2, 'Gruel'), (3, 'Wet'), (5, 'Dry'), (4, 'Wet/Dry')]),
        ),
    ]
