# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0005_auto_20160107_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitten',
            name='lastWeight',
            field=models.IntegerField(db_column='lastWeight'),
        ),
    ]
