# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0006_auto_20160321_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitten',
            old_name='lastWeight',
            new_name='pre_feed',
        ),
        migrations.AddField(
            model_name='kitten',
            name='post_feed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
