# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0007_auto_20160321_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='bathroom',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='post_feed',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
